### ISSUE TITLE
whatsapp authentication via QR Code

### ISSUE THREAD

**Issue by UmutAlihan** [onderceylan/puppeteer-demos#2]
Merhabalar,

"Puppeteer can automate that!" konuşmanızı dinledim. Emeğinize sağlık, çok teşekkürler.

Whatsapp otomasyonunu ben de denemiştim. Evdeki serverımda 1 kere manuel QR Code ile login olup açık bıraktığım session üzerinden çalışıyordum.  QR Authentication kısmını otomatikletirebildiniz mi?

**Comment by onderceylan** [comment]
Selam @UmutAlihan, tesekkurler izledigin icin. QR auth otomatiklestirmek biraz zor, o yuzden simdilik manuel authenticate olup, session'i tutan user klasorunu bulut sunucuya yukluyorum yaklasik 3 haftada bir.

Otomatiklestirilebilir elbet ama sunlar gerekli;

* Auth olmus bir mobil cihaz simulasyonu, ki QR kod sadece mobil uygulamadan okutulabiliyor.
* Gelen QR kodu resmini push mesaji veya email ile kullaniciya gonderme.
* Her 10-15 sn'de bir bu QR kodu degisiyor, dolayisiyla hizli reaksiyon sart.

Benim gozlemledigim kadariyla bu sartlarin hepsini saglayabilirsek ancak olabilir. Senin bir onerin var mi cozum icin?

**Comment by UmutAlihan** [comment]
Selam, 

Mobil cihaz ihtiyacini nasil kaldirabiliriz onu henuz cozemedim. O yuzden acikcasi onerdiginiz gibi cozum aklima gelmisti.

**Comment by onderceylan** [comment]
Buna WhatsApp'in mimarisi izin vermiyor gibi gorunuyor, o yuzden simdilik kapatiyorum talebi.
